version: '3.7'
services:
  satellite-puzzle-proxy:
    image: nginx:1.15.8-alpine
    environment:
      LANG: ja_JP.UTF-8
    volumes:
      - ./conf/dev/404.html:/usr/share/nginx/html/404.html
      - ./conf/dev/50x.html:/usr/share/nginx/html/50x.html
      - ./conf/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/dev/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8880:80"
    container_name: satellite-puzzle-proxy
    links:
      - satellite-puzzle-front:satellite-puzzle-front
  satellite-puzzle-front:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    container_name: satellite-puzzle-front

