version: '3.7'
services:
  satellite-puzzle-proxy:
    image: nginx:1.15.8-alpine
    environment:
      LANG: ja_JP.UTF-8
    volumes:
      - ./conf/ssl/50x.html:/usr/share/nginx/html/50x.html
      - ./conf/ssl/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/ssl/default.conf:/etc/nginx/conf.d/default.conf
      - ./wildcard.app.tellusxdp.com.crt:/etc/nginx/wildcard.app.tellusxdp.com.crt
      - ./wildcard.app.tellusxdp.com.key:/etc/nginx/wildcard.app.tellusxdp.com.key
    ports:
      - "80:80"
      - "443:443"
    container_name: satellite-puzzle-proxy
    links:
      - satellite-puzzle-front:satellite-puzzle-front
  satellite-puzzle-front:
    build:
      context: ../front
      dockerfile: "../.docker/Dockerfile"
      args:
        NODE_ENV: $NODE_ENV
    container_name: satellite-puzzle-front
    volumes:
      - satellite-puzzle-storage:/app/src/static/images
    links:
      - satellite-puzzle-image-processing
  satellite-puzzle-image-processing:
    build:
      context: ../image_processing
      dockerfile: "../.docker/image.Dockerfile"
    expose:
      - "5000"
    container_name: satellite-puzzle-image-processing
    volumes:
      - /var/biwa.tif:/var/biwa.tif
      - /var/tokyo.tif:/var/tokyo.tif
      - /var/sado.tif:/var/sado.tif
      - satellite-puzzle-storage:/app/dst

volumes:
  satellite-puzzle-storage:
    driver: local

