version: '3.7'
services:
  satellite-puzzle-proxy:
    image: nginx:1.15.8-alpine
    environment:
      LANG: ja_JP.UTF-8
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"
    volumes:
      - ./conf/dev/50x.html:/usr/share/nginx/html/50x.html
      - ./conf/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/dev/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${PORT}:80"
    container_name: satellite-puzzle-proxy
    links:
      - satellite-puzzle-front:satellite-puzzle-front
  satellite-puzzle-front:
    build:
      context: ../front
      dockerfile: "../.docker/Dockerfile"
      args:
        NODE_ENV: $NODE_ENV
    container_name: satellite-puzzle-front
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"
    volumes:
      - satellite-puzzle-storage:/app/src/static/images
    links:
      - satellite-puzzle-image-processing
  satellite-puzzle-image-processing:
    build:
      context: ../image_processing
      dockerfile: "../.docker/image.Dockerfile"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "50"
    expose:
      - "5000"
    container_name: satellite-puzzle-image-processing
    volumes:
      - satellite-puzzle-storage:/app/dst

volumes:
  satellite-puzzle-storage:
    driver: local

